### PR TITLE
Add passport-snapchat strategy and documentation

### PR DESCRIPTION
**Pull request by nicholasgonzalezsc**
**Background**
Snapchat recently released [Login Kit for web and server flows](https://docs.snapchat.com/docs/login-kit/#web). Given that Snapchat is a popular application with a large user base, it would be helpful to include it in the documentation for developers that would like to integrate with it. 

**Changes**
- Adds SnapchatStrategy documentation 
- Add `passport-snapchat` to packages

### CODE REVIEW

**Comment by nicholasgonzalezsc** [comment]
@jaredhanson Thoughts on including this change on the passportjs website?

**Comment by jaredhanson** [comment]
What about just adding it to the strategy search?  The docs prioritize information related to the most common IdPs used for authentication, and I don't see too many sites using Snapchat for that purpose.

**Comment by nicholasgonzalezsc** [comment]
Thanks for taking a look @jaredhanson! Yes, Snapchat’s Login Kit for web launched less than a month ago (Nov 8, 2018), so it makes sense that you haven’t seen many integrations yet.

Not sure what the general policy is for which auth strategies end up on the docs pages vs. search pages — so I’m happy to make the changes if you decide keeping it on search is the right move — but, if you don’t mind, let me provide an argument for why it may be worthwhile to highlight:

Snapchat is one of the largest social media applications around, with *over 186M daily active users* largely skewing towards a younger demographic, so the number of integrations will likely grow quickly. In addition to gaining access to one of the harder to capture demographics, one of the main benefits of Snapchat's Login Kit is user privacy, as it doesn't expose unnecessary PII and provides the user with very granular permission/scope settings.

For context, here is how Snapchat's DAU compares to the other featured auth providers listed on the website based on the most recent numbers I could find:
- Github Total Users 31M
- Twitter DAU ~145M-160M 
- LinkedIn MAU ~250M, but real usage may be ~140M
- Facebook DAU ~1.5B

As you can see based on the active user numbers and access to the generally younger user base, integrating with Snapchat is a pretty compelling argument. As awareness of Login Kit and other Snap Kit sdks increases, I think it will become one of the more common integrations. 

Obviously, by placing the `passport-snapchat` package within the passportjs documentation, you will help increase the awareness of this platform, but I think that it will be a welcome addition since most developers are looking to integrate the most popular platform auth integrations and generally look to the passportjs webpage first to see what's available.

**Comment by jaredhanson** [comment]
I've added `passport-snapchat` to the strategy search.  I think that is sufficient for now to facilitate discovery.  Thanks for the contribution.

Closing.

**Pull request closed without merging**
