### PR TITLE
Adding passport-fellowshipone provider to list

### PR DESCRIPTION
**Pull request by hairyhenderson**
Hi, I'd like to get the Fellowship One strategy added to the list.

Thanks!

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@jaredhanson - any chance of getting this merged?

**Comment by jaredhanson** [comment]
This was added at some point in the past. Closing.

**Comment by hairyhenderson** [comment]
> This was added at some point in the past.

er, no it wasn't 😅... No matter - I've long since abandoned that provider.

**Comment by jaredhanson** [comment]
It's right here: https://www.passportjs.org/packages/passport-fellowshipone/

**Comment by hairyhenderson** [comment]
Ah. I was looking here: https://github.com/passport/www.passportjs.org/blob/master/docs/providers.md

Either way, it may be worth removing it now - I was working with it actively 6yrs ago but it's been effectively dead for the past 3-4yrs...

**Pull request closed without merging**
